version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - backend

  app:
    build: .
    container_name: node_app
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - backend

networks:
  backend:
    driver: bridge
